impl/src/attr.rs, tests/test_display.rs
=> Accept `.var` shorthand inside of parens

impl/src/attr.rs, impl/src/expand.rs
This refactor is a better foundation for later building validation on attributes. Doesn't yet fix #6 or #14, but is in that direction.
=> Uniformly parse all attributes in all positions

impl/src/ast.rs, impl/src/expand.rs, impl/src/lib.rs
This is further groundwork for performing more extensive validation on the macro input. This is a refactor only, with no intended change in behavior.
=> Introduce data structures to make validations easier

impl/src/expand.rs, impl/src/lib.rs, impl/src/prop.rs, impl/src/valid.rs
This reduces complexity by eliminating fallible code from expand.rs, especially as we add more validations later.
=> Perform all validation up front

impl/src/expand.rs, impl/src/prop.rs
Continues to remove complexity from expand.rs to keep it purely focused on code generation.
=> Move more tree analysis logic out of expand.rs

impl/src/prop.rs, tests/test_source.rs
=> Assume #[source] attribute for fields named `source`

.travis.yml, impl/src/expand.rs, impl/src/prop.rs, tests/test_option.rs
=> Support Option<Source> and Option<Backtrace>

impl/src/attr.rs, impl/src/expand.rs, impl/src/lib.rs, impl/src/prop.rs, impl/src/valid.rs, tests/test_from.rs, tests/ui/from-not-source.rs, tests/ui/from-not-source.stderr
Fixes #2.
This PR introduces an attribute `#[from]` that opts in to a `From` impl from the requested type.
```rust
use thiserror::Error;
pub enum Error {
Io(#[from] io::Error),
Json(#[from] serde_json::Error),
Regex(#[from] regex::Error),
Other(#[from] anyhow::Error),
}
```
We only permit `From` to be derived from the error's source field, not any arbitrary other field. Notice that this allows `#[from]` to imply `#[source]` so you don't need to also specify `#[source]` explicitly.
=> Generate From<$source> impls

impl/src/attr.rs, impl/src/expand.rs, src/lib.rs
This can collide with enum variant field names. Namespace with a
`_thiserror_` prefix to avoid such collisions.
=> display: avoid using `formatter`

Cargo.toml, impl/src/attr.rs, impl/src/expand.rs, impl/src/fmt.rs, src/display.rs, src/lib.rs, tests/test_path.rs
Based on https://github.com/dtolnay/case-studies/blob/master/autoref-specialization/README.md.
=> Support interpolating paths as if they had a Display impl

impl/Cargo.toml, impl/src/ast.rs, impl/src/attr.rs, impl/src/fmt.rs, tests/test_display.rs
a.k.a. `{ident}` for identifiers that are something other than fields of the current struct or variant.
```rust
const LIMIT: usize = 999;
#[error("value is too big: {val}, must be < {LIMIT}")]
struct Demo {
val: usize,
}
```
=> Support referring to statics and consts from shorthand

impl/src/ast.rs, impl/src/attr.rs, impl/src/expand.rs, impl/src/prop.rs, impl/src/valid.rs, tests/test_transparent.rs
This is useful for hiding error variants from a library's public error type:
```rust
#[error(transparent)]  // source and Display delegate to ErrorKind
pub struct Error(ErrorKind);
/*private*/ enum ErrorKind {
#[error("...")]
E0,
#[error("...")]
E1(#[source] io::Error),
}
```
And also for enums that need an "anything else" variant; such variants tend not to have their own Display message but just forward through to the underlying error's Display and source:
```rust
pub enum MyError {
...
#[error(transparent)]
Other(#[from] anyhow::Error),  // source and Display delegate to anyhow::Error
}
```
Closes #40.
=> Add transparent attribute for delegating Error impl to one field

impl/src/expand.rs, tests/test_deprecated.rs
=> Allow matches to refer to deprecated variants

impl/src/ast.rs, impl/src/expand.rs, tests/ui/missing-display.stderr
Before:
```console
error[E0277]: `MyError` doesn't implement `std::fmt::Display`
--> $DIR/missing-display.rs:3:10
|
3 | #[derive(Error, Debug)]
|          ^^^^^ `MyError` cannot be formatted with the default formatter
|
= help: the trait `std::fmt::Display` is not implemented for `MyError`
```
After:
```console
error[E0277]: `MyError` doesn't implement `std::fmt::Display`
--> $DIR/missing-display.rs:4:1
|
4 | pub enum MyError {
| ^^^^^^^^^^^^^^^^ `MyError` cannot be formatted with the default formatter
|
= help: the trait `std::fmt::Display` is not implemented for `MyError`
```
Closes #75.
=> Improve span of missing Display impl error

impl/src/ast.rs, impl/src/attr.rs, impl/src/valid.rs, tests/test_display.rs
Fixes #86.
This is a workaround for https://github.com/rust-lang/rust/issues/43081. The tokens were coming in with all spans erased (`#0 bytes(0..0)`) due to the compiler bug, and so the call_site spans that we used in the generated `match` expression in the Display impl were not resolving the same as identifiers generated from the macro input. The workaround is to grab a fairly arbitrary span from the macro input (I chose the span of the format string) and use that for all new bindings in `match`. This way, ordinarily that span is going to have the same hygiene context as call_site, but if https://github.com/rust-lang/rust/issues/43081 is happening then it will be #0 hygiene the same as the input tokens.
=> Reconstruct span information lost by compiler

.github/workflows/ci.yml, impl/src/expand.rs, tests/compiletest.rs, tests/test_deprecated.rs, tests/test_display.rs, tests/test_error.rs, tests/test_expr.rs, tests/test_from.rs, tests/test_option.rs, tests/test_path.rs, tests/test_source.rs, tests/test_transparent.rs
=> Try to catch clippy::pedantic violations in generated code

impl/src/expand.rs, tests/test_lints.rs
Expansion of derive(Error) macro can't know whether something like std::error::Error is already imported in the caller's scope so it must emit qualified paths and suppress unused_qualifications.
Fixes #91.
=> Suppress unused_qualifications lint

tests/test_backtrace.rs
This has worked by accident ever since thiserror 1.0.2 but was never tested.
FYI @jmaessen @edwinsmith
=> Add test involving Arc<Backtrace>

impl/src/expand.rs, tests/test_backtrace.rs
Arc\<Backtrace\> is important because it enables error types that implement Clone, since Backtrace itself cannot be cloned.
=> Generalize backtrace capture to From<Backtrace> types, including Arc<Backtrace>

impl/src/fmt.rs, tests/test_display.rs
Fixes #96 by stripping the "r#" prefix from format variables.
Previously, given a type like
```rust
#[error("a raw ident: {r#reserved}")]`
struct RawError {
r#reserved: String,
}
```
`thiserror` would output something like
```rust
// ...
Self { r#reserved } = self;
write!("a raw ident: {r#reserved}", r#reserved = r#reserved);
// ...
```
This would fail during `write!()` expansion because the character `#` isn't allowed in named `format!()` parameters.
This PR replaces the `r#` prefix with `raw_field_` when generating named parameters, producing output like
```rust
// ...
Self { r#reserved } = self;
write!("a raw ident: {raw_field_reserved}", raw_field_reserved = r#reserved);
// ...
```
The generated named parameters could collide with user-defined named parameters. …
=> Support raw-identifier fields in format strings

impl/src/fmt.rs, tests/test_display.rs
The standard library's format macros allow keyword named argument, as in `format_args!("{type}", type = 1)`. These were previously crashing thiserror.
```console
error: proc-macro derive panicked
--> tests/test_display.rs:269:14
|
269 |     #[derive(Error, Debug)]
|              ^^^^^
|
= help: message: called `Result::unwrap()` on an `Err` value: Error("expected identifier")
```
=> Fix keyword as fmt argument

README.md, src/lib.rs
Tiny change. But just using the newer, simpler and nicer constants.
=> Use i32::MAX instead of i32::max_value()

impl/src/valid.rs, tests/ui/lifetime.rs, tests/ui/lifetime.stderr
=> Detect non-static lifetime behind reference type parameter

impl/src/expand.rs, tests/test_source.rs
When a macro generates part of the derive input, the call-site hygiene
may be different than the hygiene of a field. Therefore, we need to
be sure to use the same hygiene information for any identifiers we
generate, instead of relying on the hygiene from a particular span
via `quote_spanned!`
=> Consistently use `quote!` when emitting 'source'

src/aserror.rs, tests/test_transparent.rs
=> Support non-static lifetime inside error(transparent)

README.md, impl/src/expand.rs, impl/src/prop.rs, src/lib.rs, tests/test_backtrace.rs
This implements support for `#[from]` and `#[backtrace]` attributes used together on the same field. The purpose is to forward the `backtrace()` implementation to the source rather than capturing a new backtrace at conversion time.
This was suggested in @dtolnay's comment "I would be prepared to consider a PR that does ..." https://github.com/dtolnay/thiserror/pull/93#pullrequestreview-666213667.
=> Combined from and backtrace field

impl/src/expand.rs, tests/test_from.rs
This allows `?` to work with error types that only sometimes have a source (as seen in #1).
```rust
use std::io;
use thiserror::Error;
#[error("...")]
pub struct Error {
#[from]
source: Option<io::Error>,
}
fn main() -> Result<(), Error> {
io::copy(&mut io::empty(), &mut io::sink())?;
Ok(())
}
```
=> Support #[from] on an Option field

impl/src/ast.rs, impl/src/attr.rs, impl/src/expand.rs, impl/src/fmt.rs, impl/src/generics.rs, impl/src/lib.rs, tests/test_generics.rs
Closes #79. This PR enables an error type with generic parameter(s):
```rust
enum MyError<E, F> {
#[error("thing {0}")]
Variant(E),
#[error("some error")]
Delegate(#[source] F),
}
```
to emit appropriate impls, without further manual intervention to provide handwritten trait bounds. In the above case namely:
```rust
impl<E, F> Error for MyError<E, F>
where
F: Error + 'static,
Self: Debug + Display;
impl<E, F> Display for MyError<E, F>
where
E: Display;
```
Implied bounds for `error(transparent)` are being done in an upcoming PR.
=> Implied bounds for Display and Error impl

impl/src/expand.rs, tests/test_generics.rs
This is the remaining piece of #79.
The field of a transparent variant is required to implement Display and Error (not necessarily 'static), since we delegate those two traits to it.
```rust
enum MyError<E> {
#[error(transparent)]
Delegate(#[from] E),
}
```
```rust
// generated
impl<E> Error for MyError<E>
where
E: Error,
Self: Debug + Display;
impl<E> Display for MyError<E>
where
E: Display;
impl<E> From<E> for MyError<E>;
```
=> Implied bounds for transparent attribute

impl/src/attr.rs, impl/src/fmt.rs
For example, the following needs the generated `Display` impl to have `where T: Octal + Pointer`.
```rust
enum MyError<T> {
#[error("{0:o}")]
Oct(T),
#[error("{0:p}")]
Ptr(T),
}
```
=> Implied bounds for the remaining std::fmt traits

impl/src/expand.rs, impl/src/generics.rs
This PR enables us to generate bounds resembling `T: Display + Debug` instead of like `T: Display, T: Display, T: Debug`. It makes no difference to the type checker but deduplicated bounds are more readable in rustdoc.
=> Deduplicate inferred bounds

impl/src/expand.rs, tests/test_backtrace.rs, tests/test_option.rs
=> Expose backtrace via generic member access

tests/test_deprecated.rs
This got broken in nightly-2021-06-04 and fixed in nightly-2021-06-06.
Closes #136.
=> Re-enable deprecated variants test.

impl/src/expand.rs
From https://github.com/dtolnay/thiserror/blob/1.0.33/src/aserror.rs, the `.as_dyn_error()` method exists if the #\[source\] has a std::error::Error impl, or derefs to something with a std::error::Error impl, or derefs to `dyn Error + …` (such as `Box<dyn Error>` would do).
None of those cases require the thiserror-generated `provide` method to actually go through `dyn Error`. We can directly call the `provide` method, which will do the deref'ing and then call `provide` from either the type's std::error::Error impl or from `dyn Error`'s vtable.
This wasn't possible prior to #182 because `.backtrace()` couldn't have been called directly the same way, since anyhow::Error has a backtrace method with a different signature than std::error::Error's backtrace method (`-> &Backtrace` vs `-> …
=> Directly call source.provide instead of going through dyn error

tests/test_backtrace.rs
Just like #187 this involves a deref from `&Box<dyn Error>` to `&dyn Error` before getting the backtrace, since `Box<dyn Error>` does not implement `Error` itself.
=> Add test involving backtrace from a Box<dyn Error>

src/aserror.rs, src/lib.rs
This trait is already private so we don't need to worry about handwritten impls outside the crate, but sealing anyway is nice here because it makes clear when reading aserror.rs that all impls of this trait are visible in the thiserror source code; we don't need to study the derive macro's implementation to distinguish that it isn't emitting impls of this trait.
=> Add Sealed supertrait to private AsDynError trait

README.md, src/lib.rs
The Error trait no longer has a dedicated backtrace method.
=> Fix documentation mentioning `backtrace()` method

impl/src/attr.rs, src/lib.rs
=> Avoid calling a nonstandard write! macro that might be in scope

impl/src/attr.rs, src/lib.rs
=> Fix access to `write!` macro when `thiserror` is not in scope

build.rs, impl/src/expand.rs, src/lib.rs, src/provide.rs, tests/test_backtrace.rs, tests/test_option.rs
https://github.com/rust-lang/rust/pull/113464
=> Update to nightly's new Error::provide API

impl/src/expand.rs, src/display.rs, src/lib.rs, tests/ui/no-display.stderr
Rather than having separate traits implementing as_display method,
replace DisplayAsDisplay and PathAsDisplay traits with a AsDisplay
trait.  The difference between those two traits is in the result
returned by the as_display method.  With AsDisplay trait this is
captured by an associated type.
The main motivation for the change is making it simpler to support
no_std builds in the future.  Previously, PathAsDisplay would have to
be handled specially in such builds on the side of macro
expansion. Now, thiserror-impl doesn’t need to be aware of any
complications around AsDisplay since they are all contained in
thiserror crate.
=> Replace DisplayAsDisplay and PathAsDisplay with AsDisplay trait

impl/src/attr.rs, impl/src/expand.rs
Prefer using core crate over std in macro expansions wherever a symbol has
a stable equivalent in core.  This makes it easier to eventually support
no_std in the future once error_in_core stabilises.
=> Prefer core crate in macro expansions

impl/src/expand.rs, impl/src/prop.rs, tests/ui/source-enum-unnamed-field-not-error.rs, tests/ui/source-enum-unnamed-field-not-error.stderr, tests/ui/source-struct-unnamed-field-not-error.rs, tests/ui/source-struct-unnamed-field-not-error.stderr, tests/ui/transparent-enum-not-error.rs, tests/ui/transparent-enum-not-error.stderr, tests/ui/transparent-enum-unnamed-field-not-error.rs, tests/ui/transparent-enum-unnamed-field-not-error.stderr, tests/ui/transparent-struct-not-error.rs, tests/ui/transparent-struct-not-error.stderr, tests/ui/transparent-struct-unnamed-field-not-error.rs, tests/ui/transparent-struct-unnamed-field-not-error.stderr
This PR changes the span of the `as_dyn_error()` call to the `#[source]`, `#[from]` or `#[transparant]` attribute if it exists.
My motivation was a (to me) confusing error that actually made me think `thiserror` had a bug:
```rust
use thiserror::Error;
#[derive(Debug, Error)]
#[error("{0}")]
enum Error {
Io(#[from] std::io::Error),
Custom(#[from] String),
}
```
The error uses the span of the source member, but in this case it is unnamed. How exactly it ends up with the span of the string literal is a bit unclear to me. Maybe because the member (`0`) is used in the formatting code?
Regardless, with this PR, the error is the same but the span is changed to the attribute:
If there was no `#[source]`, `#[from]` or `#[transparent]` attribute, the member name is used as before (which in …
=> Change span of `as_dyn_error()` to point compile error at attribute.

tests/ui/missing-display.rs, tests/ui/missing-display.stderr
This test existed prior to 04b91d76462834279a323b7771b48158aba19db4.
Since 791a98eb93e08f111bd16d7ec73caf50f7225f31, we can rely on rust-src being installed.
=> Restore UI test involving missing Display impl

impl/src/ast.rs, impl/src/expand.rs
#76 shows that this used to be required in order to create a good error message, on older compilers.
From #263 it's clear that this no longer makes a difference in new compilers.
=> Delete elaborate spans on path of error trait

build.rs
Example failure mode without this PR:
```rust
#![feature(error_generic_member_access)]
#[derive(thiserror::Error, Debug)]
#[error("...")]
pub struct Error {
#[backtrace]
source: std::io::Error,
}
```
```console
$ cargo +stable check  #(expected failure)
Compiling proc-macro2 v1.0.71
Compiling unicode-ident v1.0.12
Compiling thiserror v1.0.51
Compiling quote v1.0.33
Compiling syn v2.0.43
Compiling thiserror-impl v1.0.51
Checking repro v0.0.0
error[E0432]: unresolved import `thiserror`
--> src/lib.rs:3:10
|
3   | #[derive(thiserror::Error, Debug)]
|          ^^^^^^^^^^^^^^^^ no `ThiserrorProvide` in `__private`
|
note: found an item that was configured out
--> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/thiserror-1.0.51/src/lib.rs:256:29
|
256 |     pub use …
```
=> Rerun build script on RUSTC_BOOTSTRAP change

build.rs
Implements the `thiserror` part of my suggestion in #270 / https://youtrack.jetbrains.com/issue/RUST-13133#focus=Comments-27-8708330.0-0.
=> Do not rebuild on RUSTC_BOOTSTRAP changes on nightly compiler

impl/src/lib.rs, tests/test_expr.rs
This lint got downgraded from `pedantic` to `nursery` by https://github.com/rust-lang/rust-clippy/pull/7568 so we no longer run it.
=> Remove option_if_let_else clippy suppression

build/probe.rs
I expect that this fixes #278.
Sccache looks at dep-info (the thing produced by `--emit=dep-info`) to decide what environment variables to hash into the cache key for a particular compilation. See https://github.com/mozilla/sccache/blob/v0.7.4/src/compiler/rust.rs#L1424-L1448.
```rust
// 7. Environment variables: Hash all environment variables listed in the rustc dep-info
//    output. Additionally also has all environment variables starting with `CARGO_`,
//    since those are not listed in dep-info but affect cacheability.
```
Without this PR, the following failure mode explains the symptom of #278:
1. Cargo or something else compiles thiserror with a stable compiler and RUSTC_BOOTSTRAP **set**. (Apparently RustRover likes to do this. https://youtrack.jetbrains.com/issue/RUST-13133)
2. …
=> Make env-dep:RUSTC_BOOTSTRAP get listed in probe's dep-info

build.rs
This may or may not also be necessary for #278, in addition to #279. I am not sure whether sccache will add `--emit=dep-info` itself if not already present, or if it has a way of reconstructing dep-info from an rmeta output.
=> Emit dep-info for probe.rs in case sccache needs it

impl/src/attr.rs, impl/src/fmt.rs, tests/test_display.rs
Compiler is unable to generate as efficient code for `write!(f, "text")` as it does for `f.write_str("text")`.  This PR checks if the `#[error("text")]` uses a simple string literal without the `{` and `}` characters, and without arguments, and uses `write_str` if so.
Fixes #285
=> Optimize performance for string literals in Display::fmt

build.rs
Since https://github.com/rust-lang/rust/pull/121752 in nightly-2024-03-12, rustc reports the following pair of dead_code warnings in build/probe.rs, which makes it look as though error_generic_member_access is not available when using `RUSTFLAGS=-Dwarnings` (such as in CI).
```console
warning: struct `MyError` is never constructed
--> build/probe.rs:10:8
|
10 | struct MyError(Thing);
|        ^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
warning: struct `Thing` is never constructed
--> build/probe.rs:11:8
|
11 | struct Thing;
|        ^^^^^
```
=> Make compatible with -Dwarnings

impl/src/attr.rs
#296 (unblocks https://github.com/rust-lang/rust/pull/123940)
=> Implement ToTokens without reliance on {:?}

build/probe.rs, src/aserror.rs, src/display.rs, src/lib.rs, tests/test_display.rs, tests/test_error.rs, tests/test_expr.rs, tests/test_generics.rs, tests/test_path.rs, tests/ui/fallback-impl-with-display.rs, tests/ui/lifetime.rs
This changes usage of `std::fmt` to `core::fmt` in the main crate.
The corresponding change in the derive macro crate was in #255 .
This simplifies adding support for `no_std` once `error_in_core` becomes stable.
Also changes the single use of `{std -> core}::panic::UnwindSafe`.
=> `std::fmt` -> `core::fmt`

impl/src/attr.rs, tests/test_display.rs
=> Support `.0.0` nested tuple index

README.md, src/lib.rs
=> Update documentation of #[from] and #[backtrace] attributes

impl/src/expand.rs
Because
1. They are indeed automatically derived.
2. It does not break MSRV 1.56.
3. Avoid testing `Display` and `Error` methods (and each branches inside them) for test coverage. https://github.com/rust-lang/rust/pull/120185
=> Mark `#[automatically_derived]` for generated impls

src/display.rs
The other 2 thiserror-internal helper traits are already sealed.
https://github.com/dtolnay/thiserror/blob/5088592a4efb6a5c40b4d869eb1a0e2eacf622cb/src/aserror.rs#L5
https://github.com/dtolnay/thiserror/blob/5088592a4efb6a5c40b4d869eb1a0e2eacf622cb/src/provide.rs#L4
=> Seal the private AsDisplay trait

impl/src/attr.rs, tests/ui/concat-display.stderr
The previous error implied that only a string literal is expected. But the keyword `transparent` is also accepted.
=> Improve error on malformed format attribute

.github/workflows/ci.yml, Cargo.toml, README.md, build.rs, impl/Cargo.toml
Required by recent versions of syn.
=> Raise required compiler to rust 1.61

impl/src/attr.rs
It turns out this doesn't entirely fix #331 because it looks like there are still rustc parser bugs at play. But the output produced by thiserror is now correct, and it's rustc that needs to get better at parsing it.
=> Preserve None-delimited groups inside format args

impl/src/fmt.rs
This was fixed long ago in rustc by https://github.com/rust-lang/rust/pull/66847.
=> Remove format var parsing workaround that targeted rustc 1.40 and older

impl/Cargo.toml, impl/src/fmt.rs, impl/src/lib.rs, impl/src/scan_expr.rs, tests/test_expr.rs
=> More robust scanning for fmt argument expressions

impl/src/fmt.rs
The infallible scanner has the same behavior as prior to https://github.com/dtolnay/thiserror/pull/337, which exhibits bugs like https://github.com/dtolnay/thiserror/issues/335 but that's okay because fallback is only going to be applied if the format arguments do not consist of syntactically valid expressions. This is useful for an IDE performing macro expansions while code is being typed.
=> Add infallible expr scanner fallback for scanning invalid code

impl/src/fmt.rs
Previously, if Expr::parse returned an error, the macro would fall back to the infallible codepath from https://github.com/dtolnay/thiserror/pull/340 for _all_ expressions in the format args. In this PR it first tries scanning the invalid expression using https://github.com/dtolnay/thiserror/pull/337 before falling back. The scanner is more robust for handling input in real-time as an expression is being typed.
=> Interleave Expr parsing and scanning better

impl/src/fmt.rs
This is needed for an upcoming change that disallows extra positional fmt arguments in the format string of a tuple struct or tuple variant due to ambiguity. For example in `#[error("{} {0}", $N)] Variant(i32)` it is ambiguous whether the `{0}` refers to $N vs &amp;self.0. One would need to write a named `#[error("{n} {n}", n = $N)]` for the former or a numbered `#[error("{n} {0}", n = $N)]` for the latter, both of which have an obviously unambiguous meaning.
=> Add logic to determine whether unnamed fmt arguments are present

impl/src/fmt.rs
Previously an attribute containing both `==` and an incomplete expression, like `#[error("...", a == b, c = d +)]`, was treated incorrectly as containing 2 named fmt arguments `a` and `c`, instead of only `c`.
=> Disregard equality binop in fallback parser

impl/src/fmt.rs, tests/test_display.rs, tests/ui/raw-identifier.rs, tests/ui/raw-identifier.stderr
`format_args!("{r#keyword}")` is not allowed by core::fmt's format string syntax. Thiserror shouldn't allow it either.
=> Delete support for raw identifiers inside format string

impl/src/fmt.rs
The previous implementation had weird semantics in the case of `take_int(&mut "0")`. This normally didn't arise in the course of thiserror's format string parsing because there would always be at least a `}` left in the format string after the int or ident part of an interpolation, but it did matter in an IDE context while the code is being typed.
=> Fix edge case of take_int and take_ident at end of string

impl/src/fmt.rs, impl/src/lib.rs, impl/src/unraw.rs
The core::fmt format string syntax considers `format_args!("...", r#keyword = "...")` as equivalent to `format_args!("...", keyword = "...")`. That means manipulating named argument sets as `Set<Ident>` using Ident's Ord impl doesn't make sense, as that impl considers `r#keyword` != `keyword`.
Before this PR, the following would compile successfully because thiserror would see that `fn` was already present in the user-provided named arguments, so it would not try to insert a new named argument referring to the struct field:
```rust
#[error("{fn}", fn = "...")]
pub struct Error {
r#fn: &'static str,
}
```
But in contrast, the following would not compile, due to thiserror using an incorrect comparison and not realizing that a user-provided named argument for `{fn}` …
=> Add a type for representing raw-agnostic format vars

tests/test_source.rs
Without `r#source`:
```console
error[E0599]: the method `as_dyn_error` exists for type `char`, but its trait bounds were not satisfied
--> tests/test_source.rs:72:9
|
72 |         source: char,
|         ^^^^^^ method cannot be called on `char` due to unsatisfied trait bounds
|
= note: the following trait bounds were not satisfied:
`char: std::error::Error`
which is required by `char: AsDynError<'_>`
```
=> Add test of r#source that is not Error::source

tests/test_backtrace.rs
Without `r#Backtrace`:
```console
error[E0308]: mismatched types
--> tests/test_backtrace.rs:42:14
|
42  |     #[derive(Error, Debug)]
|              ^^^^^
|              |
|              expected `std::backtrace::Backtrace`, found `not_backtrace::Backtrace`
|              arguments to this method are incorrect
|
= note: `not_backtrace::Backtrace` and `std::backtrace::Backtrace` have similar names, but are actually distinct types
note: `not_backtrace::Backtrace` is defined in the current crate
--> tests/test_backtrace.rs:26:9
|
26  |         pub struct Backtrace;
|         ^^^^^^^^^^^^^^^^^^^^
note: `std::backtrace::Backtrace` is defined in crate `std`
--> $RUSTUP_HOME/toolchains/nightly-aarch64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/backtrace.rs:108:1
|
108 | pub struct …
```
=> Add test of r#Backtrace that is not std::backtrace::Backtrace

impl/src/fmt.rs, impl/src/unraw.rs, tests/ui/unconditional-recursion.rs, tests/ui/unconditional-recursion.stderr
=> Recognize infinite recursion caused by `{self}`

tests/ui/same-from-type.rs, tests/ui/same-from-type.stderr
There should have been a test for this in #30.
Without the dedicated diagnostic from impl/src/valid.rs, the error is:
```console
error[E0119]: conflicting implementations of trait `From<std::io::Error>` for type `Error`
--> tests/ui/same-from-type.rs:3:10
|
3 | #[derive(Error, Debug)]
|          ^^^^^
|          |
|          first implementation here
|          conflicting implementation for `Error`
|
= note: this error originates in the derive macro `Error` (in Nightly builds, run with -Z macro-backtrace for more info)
```
It may make sense to look into whether we can remove the dedicated diagnostic, and rearrange some spans so that "first implementation here" and "conflicting implementation for 'Error'" actually point out the two `#[from]` attributes at play.
=> Add ui test of colliding From impls

impl/src/ast.rs, tests/test_transparent.rs
I cannot tell why this was disallowed originally. Probably just buggy implementation logic.
=> Allow error(transparent) inside an enum that has error("...")

impl/src/ast.rs, impl/src/attr.rs, impl/src/expand.rs, impl/src/prop.rs, impl/src/valid.rs, tests/test_display.rs, tests/ui/concat-display.stderr, tests/ui/duplicate-fmt.rs, tests/ui/duplicate-fmt.stderr, tests/ui/struct-with-fmt.rs, tests/ui/struct-with-fmt.stderr
Before:
```rust
pub enum Error {
#[error("{code}{}", match .message {
Some(msg) => format!(" - {}", &msg),
None => "".to_owned(),
})]
Demo { code: u16, message: Option<String> },
}
```
After:
```rust
pub enum Error {
#[error(fmt = demo_fmt)]
Demo { code: u16, message: Option<String> },
}
fn demo_fmt(code: &u16, message: &Option<String>, formatter: &mut fmt::Formatter) -> fmt::Result {
write!(formatter, "{code}")?;
if let Some(msg) = message {
write!(formatter, " - {msg}")?;
}
Ok(())
}
```
This avoids forcing allocations (or the even worse workarounds in #201) and keeps elaborate formatting logic out of the data structure.
The parameter order is designed to be usable with generic methods.
```rust
#[error(fmt = …
```
=> Implement #[error(fmt = ...)]

impl/src/expand.rs
The previous way this was written could have its meaning changed by the presence of a module or type called `thiserror`, which is different from the crate `thiserror`. The new expansion refers unambiguously to a crate.
Before:
```rust
#[derive(::thiserror::Error, Debug)]
#[error("{0}")]
pub struct Error(i32);
mod thiserror {}
```
```console
error[E0432]: unresolved import `thiserror`
--> src/main.rs:1:10
|
1 | #[derive(::thiserror::Error, Debug)]
|          ^^^^^^^^^^^^^^^^^^ could not find `__private` in `thiserror`
|
= note: this error originates in the derive macro `::thiserror::Error` (in Nightly builds, run with -Z macro-backtrace for more info)
```
After: compiles successfully.
=> Perform imports from thiserror through absolute path

impl/src/expand.rs
The previous expansion was designed to facilitate "fake std" facade modules like in https://github.com/dtolnay/thiserror/pull/64#issuecomment-612570677. That is no longer supported in the new implementation, and `Error` will always refer to the standard library Error trait.
=> Access all std types through absolute path

impl/src/expand.rs, src/lib.rs
This gives control of the meaning of `Error` in derive-generated code to the `thiserror` crate's build script and its enabled feature combinations.
=> Access Error trait exclusively through ::thiserror

build.rs, impl/src/expand.rs, src/lib.rs
This fixes a forward compatibility risk where downstream code compiles successfully against no-std thiserror by using backtraces through the downstream code's own direct dependency on std, and then later breaks if future changes to the Provider API require moving some of our backtrace handling into helper types that are exposed by thiserror which cannot be present in no-std thiserror.
=> Access Backtrace exclusively through ::thiserror

impl/src/fmt.rs, impl/src/unraw.rs
For something like:
```rust
const CODE: usize = 9;
#[error("{id:?} (code {CODE:?})")]
pub struct Error {
pub id: &'static str,
}
```
Before:
```rust
let Self { id } = self;
match (id, CODE) {
(__field_id, __field_CODE) => {
__formatter.write_fmt(format_args!("{__field_id:?} (code {__field_CODE:?})"))
}
}
```
After:
```rust
let Self { id } = self;
match (id,) {
(__field_id,) => {
__formatter.write_fmt(format_args!("{__field_id:?} (code {CODE:?})"))
}
}
```
=> Emit rebinding only for interpolations that refer to a field

impl/src/fmt.rs, tests/test_path.rs
Previously, for an error containing a Path or PathBuf, `#[error("display:{0} debug:{0:?}")]` would work but `#[error("debug:{0:?} display:{0}")]` would not compile.
```console
error[E0277]: `PathBuf` doesn't implement `std::fmt::Display`
--> tests/test_path.rs:36:13
|
32 | #[derive(Error, Debug)]
|          ----- in this derive macro expansion
...
36 |     #[error("debug:{0:?} display:{0}")]
|             ^^^^^^^^^^^^^^^^^^^^^^^^^ `PathBuf` cannot be formatted with the default formatter; call `.display()` on it
|
= help: the trait `std::fmt::Display` is not implemented for `PathBuf`
= note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
= note: call `.display()` or `.to_string_lossy()` to safely print paths, as they may contain non-Unicode data
= help: …
```
=> Support Display and Debug of same path in error message

impl/src/fmt.rs, src/var.rs, tests/ui/no-display.rs, tests/ui/no-display.stderr
This keeps a distracting mention of "Var" out of error messages when an impl is missing.
=> Use Var wrapper only for Pointer formatting

impl/src/expand.rs, tests/test_lints.rs
I think I did this correctly.
In Clippy 0.1.83, without the changes in `expand.rs`, the new test in `test_lints.rs` fails with the following output:
```
error: the following explicit lifetimes could be elided: 'a
--> tests/test_lints.rs:29:22
|
29 |     pub enum MyError<'a> {
|                      ^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes
note: the lint level is defined here
--> tests/test_lints.rs:25:13
|
25 |     #![deny(clippy::needless_lifetimes)]
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^
help: elide the lifetimes
|
29 -     pub enum MyError<'a> {
29 +     pub enum MyError'_> {
|
error: could not compile `thiserror` (test "test_lints") due to 1 previous error
```
Clippy doesn't like the generated `impl From` …
=> suppress needless_lifetimes lints from clippy 0.1.83

impl/src/expand.rs, impl/src/fallback.rs, impl/src/lib.rs
I am considering standardizing on fallback.rs across all my derive macros.
=> Move fallback expansion to separate module

impl/src/expand.rs, tests/test_lints.rs
Fixes:
error: #[allow] attribute found
--> src/lib.rs:13:26
|
13 | pub struct DownloadError(#[from] std::io::Error);
|                          ^^^^^^^ help: replace it with: `expect`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#allow_attributes
note: the lint level is defined here
--> src/lib.rs:1:9
|
1  | #![deny(clippy::allow_attributes)]
|         ^^^^^^^^^^^^^^^^^^^^^^^^
I could only repro with `RUSTC_BOOTSTRAP=1` on 1.83.0. Couldn't repro
with beta or nightly. So maybe this fix isn't worth it.
Issue is discussed at
https://github.com/rust-lang/rust-clippy/issues/13349
=> Avoid associating #[from] with lint allow

impl/src/fmt.rs, impl/src/unraw.rs, tests/test_display.rs
Fixes https://github.com/dtolnay/thiserror/issues/398.
=> Fix spans on macro-generated bindings and format variables

tests/test_expr.rs, tests/test_path.rs
Forwarded from [Debian](https://salsa.debian.org/Maytha8/debcargo-conf/-/blob/6708e05957603156efa7fd43a196422b56e57d1d/src/thiserror/debian/patches/fix-std-tests.patch).
=> Add feature gate to tests that use std

.github/workflows/ci.yml, tests/test_backtrace.rs, tests/test_expr.rs, tests/test_option.rs
Followup to https://github.com/dtolnay/thiserror/pull/409.
=> Add CI step to test with "std" disabled

build.rs
Copied from https://github.com/dtolnay/proc-macro2/pull/512
=> Allow build-script cleanup failure with NFSv3 output directory to be non-fatal

build.rs
Copied from https://github.com/dtolnay/anyhow/pull/354.
=> Make error_generic_member_access compatible with -Dwarnings
