Cargo.toml, tests/compiletest.rs, tests/ui/duplicate-fmt.rs, tests/ui/duplicate-fmt.stderr, tests/ui/missing-fmt.rs, tests/ui/missing-fmt.stderr, tests/ui/union.rs, tests/ui/union.stderr
=> Set up some trybuild tests

impl/src/ast.rs, impl/src/attr.rs, impl/src/prop.rs, impl/src/valid.rs, tests/ui/duplicate-source.rs, tests/ui/duplicate-source.stderr
=> Detect duplicate source attributes

impl/src/ast.rs, impl/src/attr.rs, tests/test_display.rs
=> Variants inherit fmt attr from the enum

impl/src/attr.rs, impl/src/fmt.rs, impl/src/valid.rs, tests/ui/unexpected-field-fmt.rs, tests/ui/unexpected-field-fmt.stderr, tests/ui/unexpected-struct-source.rs, tests/ui/unexpected-struct-source.stderr
=> Reject attributes in unrecognized places

impl/src/expand.rs, impl/src/prop.rs, tests/test_display.rs
=> Support Display impl for void enums

impl/src/attr.rs, impl/src/expand.rs, impl/src/lib.rs, impl/src/prop.rs, impl/src/valid.rs
=> Prefer the source's backtrace if it has one

src/aserror.rs, tests/test_source.rs
---
Maybe there's no need for this and I should just add `+ Sync` to my bounds as well?
=> aserror: support Send + !Sync errors too

impl/src/fmt.rs, tests/test_display.rs
=> Support mixing shorthand and non-shorthand format args

impl/src/attr.rs, tests/test_display.rs
=> Parse .0 fmt arguments in all valid places

tests/test_expr.rs
=> Add expression tests from rcc codebase

impl/src/valid.rs, tests/ui/lifetime.rs, tests/ui/lifetime.stderr
=> Add error message for non-static source

impl/src/valid.rs, tests/ui/bad-field-attr.rs, tests/ui/bad-field-attr.stderr
=> Reject transparent attr in field attribute position

impl/src/fmt.rs
This is reshuffling the `implied_bounds.insert` to come before the `continue` previously on line 83. For a format string like `error("{0:o} ~ {0:p}")` where field 0 is of type `T`, we need bounds `T: Octal + Pointer` both emitted. The short circuit on line 83 is dealing with the fact that we don't need argument 0 passed multiple times to the generated `write!` call, but it's not supposed to short circuit the implied bounds generation.
=> Handle multiple bounds from the same format string on the same field

impl/src/valid.rs, tests/ui/from-backtrace-backtrace.rs, tests/ui/from-backtrace-backtrace.stderr
=> Fix miscounting fields when from and backtrace are same field

tests/ui/multiple-provide.rs, tests/ui/multiple-provide.stderr
Test for #185. This will need to get converted to a regression test once the problem is fixed.
=> Add temporary ui test of 'multiple applicable items' error

Cargo.toml, tests/test_backtrace.rs
This requires both https://github.com/dtolnay/anyhow/pull/268 and https://github.com/dtolnay/thiserror/pull/184.
=> Add test of getting backtrace from an anyhow source

Cargo.toml, tests/test_backtrace.rs
Pulls in https://github.com/dtolnay/anyhow/pull/271 as followup to #190.
=> Pull in Provider impl from anyhow 1.0.65

Cargo.toml, tests/test_backtrace.rs
Changes from https://github.com/dtolnay/anyhow/pull/319.
=> Pull in anyhow's new Error::provide support

build.rs
This should have been in #272.
=> Rerun build script on changes to probe.rs

impl/src/fmt.rs, tests/test_generics.rs
Fixes https://github.com/dtolnay/thiserror/issues/345.
=> Only apply inferred bounds if interpolation refers to field

impl/src/valid.rs
This code is superseded by the impl from https://github.com/dtolnay/thiserror/pull/352.
=> Remove same_member in favor of MemberUnraw's PartialEq impl

impl/src/fmt.rs, tests/ui/expression-fallback.rs, tests/ui/expression-fallback.stderr
=> Fix fallback fmt expression parser hang

impl/src/expand.rs, tests/test_lints.rs, tests/ui/missing-display.stderr
=> Prevent deprecation warning on generated impl for deprecated type

impl/src/expand.rs, tests/test_lints.rs
=> Suppress deprecation warning on generated From impls
